backend:
  name: github
  repo: k-peeters/vikfit
  branch: main

media_folder: "Images/uploads"
public_folder: "/Images/uploads"

collections:
  - name: "vikposts"
    label: "Vikfit Posts"
    folder: "vikposts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Afbeelding", name: "image", widget: "image" }
      - { label: "Bericht", name: "body", widget: "markdown" }