backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "vikposts"
    label: "Vik’s Posts"
    folder: "vikposts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Foto", name: "image", widget: "image" }
      - { label: "Bericht", name: "body", widget: "markdown" }
